### ISSUE TITLE
Problem: Crossfire httpapi PANIC runtime error

### ISSUE THREAD

**Issue by foreseaz** [crypto-com/chain-indexing#290]
2021-01-12T22:03:50+08:00 ERR GET /api/v1/crossfire/validators: PANIC runtime error: invalid memory address or nil pointer dereference module=httpapi

![image](https://user-images.githubusercontent.com/5697641/104324267-30265680-5522-11eb-8c5d-0c72bedeb618.png)

**Comment by foreseaz** [comment]
![image](https://user-images.githubusercontent.com/5697641/104327475-cad46480-5525-11eb-85bc-1ae80248f97a.png)

Have set up a localhost for json file, seems not only the Github API limitation problem. @cdc-Hitesh

**Comment by cdc-Hitesh** [comment]
Noted.
Thanks @foreseaz
