### ISSUE TITLE
Problem: Current logic of "failed IBC transfer" maybe inaccurate

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-indexing#590]
Right now the IBC success count and rate is treating timeout transfer as failure. However, these timeout transfers is more of user error than relayer error. In fact in these case relayer is doing its job to relay these timeout failure correctly.

The idea of success rate should be re-defined to reflect the failure of relayer(s), but not packet timeout.

**Comment by ysong42** [comment]
I will take this issue. 🙏 

Yes, the current success rate is to indicate the ratio of `IBC Transfer` that is successfully acknowledged on the current chain (only MsgAcknowledgement count as success).

After the changes, the success rate should indicate the ratio of `IBC Transfer` that is handled by relayers (MsgAcknowledgement, MsgTimeout, MsgTimeoutOnClose will all count as success).
