### ISSUE TITLE
Finding: 2021-11-01 Re-index

### ISSUE THREAD

**Issue by ysong42** [crypto-com/chain-indexing#597]
## Partial Re-index On Specific Projections

- Transaction
- AccountMessage
- AccountTransaction
- IBCChannel (IBCChannelTxMsgTrace for staging)
- IBCChannelMessage

## Full Re-index On Clean DB  

During the re-indexing, we found some performance issues on Crypto.org Chain mainnet indexing.

<img width="392" alt="Screenshot 2021-11-03 at 11 16 54 AM" src="https://user-images.githubusercontent.com/86600130/140880658-ec728e78-7a1e-4af7-b8e0-714c734a3b3f.png">

The above image shows that, starting from a clean DB, after around 2 days of running, some projections are still catching up the latest block height.

The slowest one is the `Validator` projection, I already created a PR to improve it. #593 

There are some other projections could also be optimized, we might take a closer look into them later:
- AccountMessage
- BlockEvent
- AccountTransaction
- ValidatorStats

**Comment by calvinaco** [comment]
Moved to https://github.com/crypto-com/chain-indexing/issues/622
