### ISSUE TITLE
Problem: MsgTimeout could be relayed multiple times

### ISSUE THREAD

**Issue by ysong42** [crypto-com/chain-indexing#608]
## How do I find this?

![image](https://user-images.githubusercontent.com/86600130/141274277-a7a1b34c-621d-4ab4-b098-9b0ec404095c.png)

`Ralay out success rate` is more than 1... And it is weird that `total success` is larger than `total`...

Then I check the staging DB and find:

![image](https://user-images.githubusercontent.com/86600130/141274492-933fe8e4-6cfa-43b7-9a21-d95c56b51ace.png)

Next, go to explorer and check the related txs on explorer, I find they are using same `sequence`.

https://chain.3ona.co/explorer/croeseid4/block/1303950
https://chain.3ona.co/explorer/croeseid4/block/1303953
https://chain.3ona.co/explorer/croeseid4/block/1303954

In a word, one `MsgTransfer` (IBC Transfer) triggered two `MsgTimeout`s (IBC Packet Timeout).

## How to fix this?

I checked `ibc-go` implementation, and find the `MsgTimeout` will still show up in Block even it is relayed for the second time.

This is a similar case that we encountered before, the msg is relayed twice, and we should ignore the second one.

For the second `MsgTimeout`, the chain will do `no-op`, the refund will not occur for a second time. But the chain will still broadcast `timeout_packet` event.

Code reference:
https://github.com/cosmos/ibc-go/blob/823ef675bbf38a48faa3ba670fb6b8228d58b9fd/modules/core/keeper/msg_server.go#L552
https://github.com/cosmos/ibc-go/blob/823ef675bbf38a48faa3ba670fb6b8228d58b9fd/modules/core/04-channel/keeper/events.go#L119
https://github.com/cosmos/ibc-go/blob/823ef675bbf38a48faa3ba670fb6b8228d58b9fd/modules/core/04-channel/keeper/timeout.go#L77

Sample Block Results:
https://testnet-croeseid-4.crypto.org:26657/block_results?height=1303953 (log contains a `timeout` event)
https://testnet-croeseid-4.crypto.org:26657/block_results?height=1303954 (log not contain a `timeout` event)

I will suggest the following changes: 
- in parser function, check if `timeout` event exist in `log`
- introduce a `NoOperation` boolean field for `MsgTimeout`. And maybe also introduce this to `MsgTimeoutOnClose`, `MsgRecvPacket` and `MsgAcknowledgement`?

**Comment by calvinaco** [comment]
Adding some thoughts to this issue, in the existing design we put a `success: false` to `MsgAcknowledgement` and `MsgRecvPacket` for those which has already relayed.

I think this "assumption" of false is not quite correct and may confuse a projection that the packet really fails.

My suggestion would be

### 1. As you mention introduces new fields to the existing message events

- `success` value is ambiguous
- it requires projection to fully aware of the possibility of a duplicated message and they have to look at `NoOperation` field

### 2. Introduce `MsgAlreadyRealyedAcknowledgement` and `MsgAlreadyRelayedRecvPacket`

**Comment by calvinaco** [comment]
cc @davcrypto into this discussion

**Comment by ysong42** [comment]
> Adding some thoughts to this issue, in the existing design we put a `success: false` to `MsgAcknowledgement` and `MsgRecvPacket` for those which has already relayed.
> 
> I think this "assumption" of false is not quite correct and may confuse a projection that the packet really fails.
> 
> My suggestion would be
> 
> ### 1. As you mention introduces new fields to the existing message events
> * `success` value is ambiguous
> * it requires projection to fully aware of the possibility of a duplicated message and they have to look at `NoOperation` field
> 
> ### 2. Introduce `MsgAlreadyRealyedAcknowledgement` and `MsgAlreadyRelayedRecvPacket`

Yes, I agree. This solution is clearer. 

So the newly introduced Msgs should be:
- `MsgAlreadyRelayedAcknowledgement`
- `MsgAlreadyRelayedRecvPacket`
- `MsgAlreadyRelayedTimeout`

Might also need to check the source code later, see if a similar case exist in `MsgTimoutOnClose`.
