### ISSUE TITLE
Problem: Missing example app

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-indexing#634]
One suggestion is to put both example app and the current codebase into this repository. 

\- repository root
|- lib, current codebase
|- app-example, an example application with basic API and leveraging the `lib`

**Comment by ysong42** [comment]
I had a discussion on this with David.

David suggests only adding an extra folder under `chain-indexing` repo root. `<repo-root>/app-example`. I think this structure also works. And it saves us from updating all related import path in `chain-indexing-server`.
