### ISSUE TITLE
Problem: Missing validators last 30 days up time projection

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-indexing#667]
## Background
Right now the `validator` projection records the lifetime up-time of a validator.

## Problem
When the chain runs for a longer time, the life-time up-time may not a good reflection of the validator recent performance.

## Draft
Can we include a 30 days (in terms of blocks) up time, or even a configurable n days up-time?

**Comment by davcrypto** [comment]
Resolved on #774
