### ISSUE TITLE
Problem: Unrecognized governance proposal types should not panic

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-indexing#707]
Phase 1: Do not panic on unrecognized proposal types
Phase 2: Print error log (which requires changing the CosmosParser interface)

**Comment by vincentysc** [comment]
I have changed the code to print the error log and commented out `softwareUpgradeProposal` type to test it. Is the highlighted part is what you expected ?


<img width="774" alt="Screenshot 2022-06-30 at 3 04 41 PM" src="https://user-images.githubusercontent.com/101554944/177234832-dac65151-1e3c-4a10-8107-6c0fbc782487.png">
