### ISSUE TITLE
Problem: Missing handle for genesis too large response

### ISSUE THREAD

**Issue by vincentysc** [crypto-com/chain-indexing#726]

**Comment by davcrypto** [comment]
For some case, the tendermint genesis endpoint could return an error when the genesis is too large. Thus, there is a need to access `genesis_chunked` endpoint to construct the genesis from pieces.

### Example response
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "genesis response is large, please use the genesis_chunked API instead"
  }
}
```
